id = "papyrus"
name = "Papyrus"
version = "0.1.0"
schema_version = 1
authors = ["monster-cookie"]
description = "Starfield-first Bethesda Papyrus syntax support with an original Tree-sitter grammar"
repository = "https://github.com/monster-cookie/zed-papyrus"

[grammars.papyrus]
repository = "https://github.com/monster-cookie/zed-papyrus"
rev = "0240214113162d189ccbbf5d430427be24e76e55"
path = "grammar"
